Running suite(s): Default
94%: Checks: 18, Failures: 1, Errors: 0
public.c:81:F:Public:B_func_call3:0: Assertion 'run_program("def int add(int a, int b) { return a + b; } " "def int main() { return add(2,3) + add(4,5) + add(6,7); }") == 27' failed: run_program("def int add(int a, int b) { return a + b; } " "def int main() { return add(2,3) + add(4,5) + add(6,7); }") == 34, 27 == 27
